### ISSUE TITLE
AppVeyor build 

### ISSUE THREAD

**Issue by dpaquette** [AspNetMonsters/pugzor#19]
Just a basic compile and run unit tests should be sufficient

**Comment by mavanmanen** [comment]
This is very easy, except .net core xUnit is not supported by them at the moment is seems, can't get it working, yaml needed for a basic compilation one is this:
```yaml
version: 1.0.{build}
image: Visual Studio 2017
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
test: off
```

**Comment by dpaquette** [comment]
I have xUnit tests working in .NET Core apps on AppVeyor. 
https://github.com/dpaquette/TagHelperSamples/blob/master/appveyor.yml

**Comment by mavanmanen** [comment]
Lemme test that out, I tried nearly everything I could find, kept giving me problems

**Comment by mavanmanen** [comment]
Jup, worked with this:
```yaml
version: 1.0.{build}
image: Visual Studio 2017
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
test_script:
- ps: >-
    cd C:\projects\pugzor\Pugzor.Test\

    dotnet test
```
I feel so stupid that in the end it was that easy (spend hours trying to get it to work)
